### PR TITLE
Add datatype annotations

### PR DESCRIPTION
**Pull request by stlehmann**
This PR introduces PLCSimpleDataType and PLCDataType to make type-annotations more specific. 

Also it renames the symbol_type parameter of Connection.get_symbol to plc_datatype to fit in the pattern of functions like read or read_by_name. I hope @RobertoRoos doesn't mind this small change.

### CODE REVIEW

**Comment by RobertoRoos** [comment]
Looks good. Do the new renders properly in Sphinx documentation?

**Comment by stlehmann** [comment]
> Do the new renders properly in Sphinx documentation?

grafik

**Comment by stlehmann** [comment]
Does anyone know a way how to tell Sphinx to not solve the Type aliases? I think that is a lot of verbose information here.

**Comment by RobertoRoos** [comment]
I'll say that's not terrible clear. Can we let Sphinx not resolve the type?

**Comment by stlehmann** [comment]
> Couldn't we use something like Type[_CData] instead?

Actually I was thinking about this in the first place. All basic ctypes types are _ctypes.PyCSimpleType. But I couldn't find
the module/package from which to import it.

**Comment by stlehmann** [comment]
Putting the Type in quotation marks keeps Sphinx from expanding the type information. Looks good to me. What do you think?

**Comment by RobertoRoos** [comment]
Looks fine, good work!

**Comment by stlehmann** [comment]
Maybe in time someone comes up with a better idea then just stacking all basic ctypes together in PLCSimpleDataType I'm not too happy with the current solution but don't see a better way at the moment.

**Pull request merged**
