### PR TITLE
Added write_by_dict functionality

### PR DESCRIPTION
**Pull request by chrisbeardy**
- includes function to convert to bytes from an OrderedDict
- includes tests and docs

@stlehmann not sure if you want to tidy up or rethink the bytes_from_dict function, to make it look nicer, less complex? Can you think of any improvements to it.

### CODE REVIEW

**Comment by chrisbeardy** [comment]
@stlehmann not sure why the tests are failing now, they seem to be failing on `test_get_all_symbols_empty` which I have not changed and seems to be an issue with the ADS server? Are my new tests impacting this test?

**Comment by chrisjbremner** [comment]
That was a test I introduced in https://github.com/stlehmann/pyads/pull/155. I suspect that adding a ``time.sleep(1)` after starting the server in `setUpClass` like the `AdsConnectionClassTestCase` does would fix it. Let me give it a try in a new PR.

**Review by stlehmann — CHANGES_REQUESTED** [review]
@chrisbeardy This looks great to me. Would you mind changing the base branch for the merge to "dev"? And if you like you can add an entry to the changelog that describes the new feature.

**Review by stlehmann — APPROVED** [review]
Looks great now. Thanks for your engagement 👍

**Pull request merged**
