### PR TITLE
ready for 3.4.0 release

### PR DESCRIPTION
**Pull request by chrisbeardy**

### CODE REVIEW

**Comment by chrisbeardy** [comment]
@stlehmann Hi, I believe I have made all the changes required here to make a release to PyPi to fix a few issues. In order toi upload the PyPi, do I just run the Github Action "Release Python Package"?

**Comment by stlehmann** [comment]
> @stlehmann Hi, I believe I have made all the changes required here to make a release to PyPi to fix a few issues. In order toi upload the PyPi, do I just run the Github Action "Release Python Package"?

Great work. @chrisbeardy thank you very much for helping me maintaining this repository. Hopefully I'll find some more time to spare in the future to get more involved in the process again. In the meantime I'm more then happy to see the package being so well maintained by you :)

Yes actually the Github Action should start the release process. It could be that you get issues because github secrets are used to upload to PyPi with my credentials. But I propose you give it a try and see if it does what it should do.

**Comment by chrisbeardy** [comment]
@stlehmann thanks. I'll do my best with the time I have. I seem to have an issue making the release (PyPI saying its not accepting new users or projects I think). Can you try manually running the release action please and see if it's just because I'm running it with my account?

**Comment by stlehmann** [comment]
I had to create a PyPi API-Token for pyads before the upload worked. I stored it in the project secrets so it should work out-of-the-box for the next CI-triggered release, hopefully :)

**Pull request merged**
