### PR TITLE
Add support for testserver notifications

### LINKED ISSUE #236: Symbol device notifications in test server
I think that device notifications are not called from the test server. Could that be right?

In `tests/test_connection_class.py` there is `test_decorated_device_notification()`, which sets up a callback for a notification and the value is written to. But the print inside the callback doesn't show.

Anyone remember this having ever worked?

It could be nice to have it as a test inside pyads itself, but I also need it in a test of another application I am making.

### PR DESCRIPTION
**Pull request by RobertoRoos**
Title says it all. Fixes #236.

It might be good to merge or abort #237 first, since I continued with the branch locally. We could yank out the refactoring again if it's unwanted.

### CODE REVIEW

**Comment by stlehmann** [comment]
> It might be good to merge or abort #237 first

Yes, I think we should do that.

**Comment by RobertoRoos** [comment]
I've added more documentation on the testserver, including a big ol' warning about limited support.

**Comment by stlehmann** [comment]
#237 is merged as #243. Can you please rebase to master?

**Comment by stlehmann** [comment]
@RobertoRoos in the docs you wrote that the AdvancedTestServer adds variables by implicitly. However this is not the case. Variables need to be added explicitly to the server with add_variable(). I fixed that in the docs.

**Comment by stlehmann** [comment]
Also during refactoring you removed the original docstrings from testserver. I added them to the package.

**Comment by stlehmann** [comment]
@RobertoRoos I added module docstrings for the testserver modules. I tried to keep the original authors information. Fee free to add your mail addres to __init__.py and __main__.py

**Comment by stlehmann** [comment]
I added arguments for setting port and ip address. This makes setting up the testserver more flexible.

**Review by stlehmann — APPROVED** [review]

**Comment by RobertoRoos** [comment]
Hm, I really thought I made the implicit variables part. Maybe I removed it again.

Thanks for your contributions!

Do I still need to rebase anything? I got to say I've lost track of the Git repos. Are your commits pushed into my fork?

**Comment by stlehmann** [comment]
> Hm, I really thought I made the implicit variables part. Maybe I removed it again.

Yes you added implicit variable creation in a previous PR. I decided to stay explicit because it brings more certainty to the way the tests are written. I hope you don't mind too much 🤔

Thanks for your great effort with this PR. I think we are all set and ready to merge. 🎉

**Comment by RobertoRoos** [comment]
No, you're right. Thanks, I'm excited to use this in my own pyads applications.

**Pull request merged**
