### PR TITLE
bug fix for setting up remote route from linux

### PR DESCRIPTION
**Pull request by chrisbeardy**
alternative solution from #97  for #66 (and deriative)

This or #97 could be implemented as a quick hotfix for the setting up route from linux issue. 

This one just removes the ability to change the route_name, so is essentially like not using the optional inputs of the function. Breaks backward compaibilty but this is aimed a being a hot_fix.

@Adrian-at-CrimsonAuzre what do you think?

### CODE REVIEW

**Comment by chrisbeardy** [comment]
p.s. not sure why 3.7 build failed...may pass if forced built again as odd port is use error

**Comment by stlehmann** [comment]
Did someone so far try one of the two fixes? @chrisbeardy which one would you prefer?

**Comment by chrisbeardy** [comment]
> Did someone so far try one of the two fixes? @chrisbeardy which one would you prefer?

I have't tried although it seems that @blindidiotscout was using TC2 when they got the same error and could fix it by swapping the two still. The simplest fix is #97, just swapping the two around. This may have just been a simple error in the first place.

**Comment by chrisbeardy** [comment]
closing as tested other solution

**Pull request closed without merging**
