### PR TITLE
bug fix for setting up route on linux with documentation clarifications

### PR DESCRIPTION
**Pull request by chrisbeardy**
fix for adding route to PLC with TwinCat 2 and 3 from Linux

### CODE REVIEW

**Comment by chrisbeardy** [comment]
duplicate of #134

**Comment by chrisbeardy** [comment]
not sure why that failed the CI test on python 3.8, I'd rerun the test as it passed earlier on #134 and is passing on other python versions.

**Comment by stlehmann** [comment]
This was quite a ride. But looks great, now. I'll merge. Thanks :)

**Comment by chrisbeardy** [comment]
Yer, sorry about that, I was struggling with pycharm, for some reason no matter what I was doing I just couldn't get it to configure the line endings, it wasn't recognising the diffs.

**Pull request merged**
